// Generated by Tools/build-brand.py from thmanyahserifdisplay-Bold.otf. Do not edit.
//
// The menu bar mark is ح, drawn rather than loaded. A second SwiftPM resource
// bundle would have to be found at runtime inside the packaged .app the way
// CoreResources.swift already finds the language models, and copied in by the
// Makefile the way that one is — real cost, for one small letter. Outlines
// compiled into the binary cannot go missing.
//
// The font it came from is not in this repository and may not be: its licence
// permits the letterform in a logo and forbids redistributing the font
// software. Rerun the generator with `make brand` to change the face.

import AppKit

/// Harf's status item image: the letter ح, as a template so AppKit tints it
/// for the menu bar's appearance and for selection.
enum MenuBarGlyph {
    /// The point size AppKit gives a status item's image.
    static let size = NSSize(width: 18, height: 18)

    /// The letter, in a 18×18 box whose origin is at the bottom left —
    /// the orientation Core Graphics and an unflipped `NSImage` both use, so
    /// the path needs no transform at draw time.
    static func path() -> NSBezierPath {
        let path = NSBezierPath()
        path.move(to: NSPoint(x: 4.689, y: 12.715))
        path.line(to: NSPoint(x: 4.818, y: 12.586))
        path.curve(to: NSPoint(x: 6.657, y: 12.859), controlPoint1: NSPoint(x: 5.436, y: 12.744), controlPoint2: NSPoint(x: 5.838, y: 12.859))
        path.curve(to: NSPoint(x: 8.799, y: 12.657), controlPoint1: NSPoint(x: 7.39, y: 12.859), controlPoint2: NSPoint(x: 8.109, y: 12.772))
        path.curve(to: NSPoint(x: 4.559, y: 7.584), controlPoint1: NSPoint(x: 6.356, y: 11.666), controlPoint2: NSPoint(x: 4.559, y: 10.099))
        path.curve(to: NSPoint(x: 9.949, y: 3), controlPoint1: NSPoint(x: 4.559, y: 4.523), controlPoint2: NSPoint(x: 7.232, y: 3))
        path.line(to: NSPoint(x: 13.441, y: 4.954))
        path.line(to: NSPoint(x: 13.441, y: 5.199))
        path.line(to: NSPoint(x: 10.164, y: 5.199))
        path.curve(to: NSPoint(x: 4.832, y: 7.642), controlPoint1: NSPoint(x: 6.657, y: 5.199), controlPoint2: NSPoint(x: 4.832, y: 6.047))
        path.curve(to: NSPoint(x: 12.679, y: 12.284), controlPoint1: NSPoint(x: 4.832, y: 10.028), controlPoint2: NSPoint(x: 8.986, y: 12.169))
        path.line(to: NSPoint(x: 12.665, y: 12.284))
        path.line(to: NSPoint(x: 12.737, y: 12.284))
        path.line(to: NSPoint(x: 13.139, y: 13.764))
        path.line(to: NSPoint(x: 13.067, y: 13.922))
        path.line(to: NSPoint(x: 12.119, y: 13.922))
        path.curve(to: NSPoint(x: 6.772, y: 15), controlPoint1: NSPoint(x: 9.647, y: 13.922), controlPoint2: NSPoint(x: 8.138, y: 15))
        path.curve(to: NSPoint(x: 5.048, y: 14.253), controlPoint1: NSPoint(x: 6.083, y: 15), controlPoint2: NSPoint(x: 5.508, y: 14.727))
        path.close()
        path.windingRule = .nonZero
        return path
    }

    static func image() -> NSImage {
        let image = NSImage(size: size, flipped: false) { _ in
            NSColor.black.setFill()
            path().fill()
            return true
        }
        image.isTemplate = true
        image.accessibilityDescription = "Harf"
        return image
    }
}
