// Generated by Tools/build-brand.py from thmanyahsans-Bold.otf. Do not edit.
//
// The menu bar mark is ح, drawn rather than loaded. A second SwiftPM resource
// bundle would have to be found at runtime inside the packaged .app the way
// CoreResources.swift already finds the language models, and copied in by the
// Makefile the way that one is — real cost, for one small letter. Outlines
// compiled into the binary cannot go missing.
//
// The font it came from is not in this repository and may not be: its licence
// permits the letterform in a logo and forbids redistributing the font
// software. Rerun the generator with `make brand` to change the face.

import AppKit

/// Harf's status item image: the letter ح, as a template so AppKit tints it
/// for the menu bar's appearance and for selection.
enum MenuBarGlyph {
    /// The point size AppKit gives a status item's image.
    static let size = NSSize(width: 18, height: 18)

    /// The letter, in a 18×18 box whose origin is at the bottom left —
    /// the orientation Core Graphics and an unflipped `NSImage` both use, so
    /// the path needs no transform at draw time.
    static func path() -> NSBezierPath {
        let path = NSBezierPath()
        path.move(to: NSPoint(x: 7.146, y: 13.089))
        path.curve(to: NSPoint(x: 9.287, y: 12.83), controlPoint1: NSPoint(x: 7.52, y: 13.089), controlPoint2: NSPoint(x: 8.238, y: 12.959))
        path.curve(to: NSPoint(x: 4.602, y: 7.211), controlPoint1: NSPoint(x: 6.988, y: 11.766), controlPoint2: NSPoint(x: 4.602, y: 9.898))
        path.curve(to: NSPoint(x: 9.675, y: 3), controlPoint1: NSPoint(x: 4.602, y: 4.796), controlPoint2: NSPoint(x: 6.528, y: 3))
        path.curve(to: NSPoint(x: 13.757, y: 3.747), controlPoint1: NSPoint(x: 11.069, y: 3), controlPoint2: NSPoint(x: 12.665, y: 3.359))
        path.line(to: NSPoint(x: 13.398, y: 5.616))
        path.curve(to: NSPoint(x: 9.819, y: 5.069), controlPoint1: NSPoint(x: 12.622, y: 5.386), controlPoint2: NSPoint(x: 11.084, y: 5.069))
        path.curve(to: NSPoint(x: 6.126, y: 7.57), controlPoint1: NSPoint(x: 7.52, y: 5.069), controlPoint2: NSPoint(x: 6.126, y: 6.119))
        path.curve(to: NSPoint(x: 13.211, y: 12.528), controlPoint1: NSPoint(x: 6.126, y: 9.97), controlPoint2: NSPoint(x: 9.862, y: 11.881))
        path.line(to: NSPoint(x: 13.24, y: 12.528))
        path.line(to: NSPoint(x: 13.24, y: 14.181))
        path.line(to: NSPoint(x: 12.578, y: 14.181))
        path.curve(to: NSPoint(x: 7.189, y: 15), controlPoint1: NSPoint(x: 9.762, y: 14.181), controlPoint2: NSPoint(x: 8.727, y: 15))
        path.curve(to: NSPoint(x: 4.243, y: 12.729), controlPoint1: NSPoint(x: 5.594, y: 15), controlPoint2: NSPoint(x: 4.703, y: 14.138))
        path.line(to: NSPoint(x: 5.565, y: 11.939))
        path.curve(to: NSPoint(x: 7.146, y: 13.089), controlPoint1: NSPoint(x: 5.838, y: 12.428), controlPoint2: NSPoint(x: 6.298, y: 13.089))
        path.close()
        path.windingRule = .nonZero
        return path
    }

    static func image() -> NSImage {
        let image = NSImage(size: size, flipped: false) { _ in
            NSColor.black.setFill()
            path().fill()
            return true
        }
        image.isTemplate = true
        image.accessibilityDescription = "Harf"
        return image
    }
}
